exp_id: EX_04
epic: 1
description: "solo blurred generation"
date: 2026-04-08
owner: sodi
# override any defaults.yaml values below this line
seed: 42
img_size: 28
raw_dir: Raw
grad_dir: ../EX_01/Raw/gradients
csv_path: ../EX_01/Raw/pairings.csv
batch_size: 512
variants:
  a:
    description: "a 3 channel just generator"
    alpha: -0.55
    beta: 0.45
    dropout_rate: 0.5
    sparse_lambda: 0.2
    blur_kernel_size: 3
  b:
    description: "a 3 channel just generator with pre-loss"
    alpha: -0.55
    beta: 0.45
    dropout_rate: 0.5
    sparse_lambda: 0.2
    blur_kernel_size: 3
  c:
    description: "a 3 channel just generator"
    alpha: -0.55
    beta: -0.45
    dropout_rate: 0.5
    sparse_lambda: 0.2
    blur_kernel_size: 3